spring.profiles.active: production

server:
  port: 808
  
logging:
  level:
    root: trace
    '[demo.application]': trace 
    '[org.springframework]': info
    '[org.apache]': info
    '[sun.rmi]': info
    '[java]': info
    '[javax]': info
    '[reactor]': info
    '[io.netty]': info
    
ioConfig:
  geo:
    host: 'http://api.openweathermap.org'
    path:
      searchGeo: '/geo/1.0/direct'
    